config/routes.rb
Rails.application.routes.draw do
  root 'mdbs#index'
  resources 'mdbs', only: :index do
    collection { post :import }
    get 'download'
    get 'destroy'
    get 'analyze'
  end

  get 'charts/show'
  post 'charts/create'

end

app/models/mdb.rb
class Mdb < ActiveRecord::Base
  def self.import(file)
    mdb = Mdb.new
    mdb.file_name = file.original_filename
    mdb.file = file.read
    mdb.save if File.extname(mdb.file_name) == ".mdb"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
# -*- coding: utf-8 -*-
require 'open-uri'
require 'json'

class ChartsController < ApplicationController
  protect_from_forgery :except => [:create] #:charts_action

  include IdentifyGraph

  @@charts = []
  def show
    @charts = @@charts
    @@charts = [] #一度出力したら初期化

  end

  def create
    #response = open("http://localhost:5000/result")
    response = open('https://java-psp-analysis.herokuapp.com/result')
    data = response.read
    @json = JSON.parse(data)
    @json.each do |key,value|
      h = LazyHighCharts::HighChart.new("graph") do |f|
        f = create_graph(f,value)
        #戻り値の関係なのか，最後にtype指定しないと上手くグラフtypeが切り替わらない．
        f.chart(:type => value["type"])
      end
      @@charts << h
    end
    redirect_to :action => "show"
  end
end

app/controllers/mdbs_controller.rb
# -*- coding: utf-8 -*-
require 'json'

class MdbsController < ApplicationController
  def index
    @mdbs = Mdb.all
    respond_to do |format|
      format.html
      format.json {render "index", :formats => [:json],:handlers => [:jbuilder]}
    end

  end

  def import
    Mdb.import(params[:file])
    redirect_to root_url, notice: "追加しました"
  end

  def download
    data_file = Mdb.find(params[:mdb_id])
    send_data(data_file.file,
      filename: data_file.file_name)
  end

  def destroy
    @mdb = Mdb.find(params[:mdb_id])
    @mdb.destroy
    respond_to do |format|
      format.html {redirect_to root_url, notice: "successfully destroyed"}
    end
  end

  def analyze
    @mdb = Mdb.find(params[:mdb_id])
    respond_to do |format|
      format.json {render "analyze", :formats => [:json],:handlers => [:jbuilder]}
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/mdbs_helper.rb
module MdbsHelper
end

app/views/charts/show.html.erb
<h1>Charts#show</h1>
<% @charts.each.with_index do |h,index| %>
	<%= high_chart("sample#{index}", h) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PSPAnalysis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mdbs/index.html.erb
<h1>Mdbs#index</h1>
<% @mdbs.each do |f| %>
	<tr>
		<td><%=  f.file_name %></td>
		<td><%= link_to 'Download', mdb_download_path(f) %></td>
		<td><%= link_to 'Destory', mdb_destroy_path(f) %></td>
		<td><%#= link_to 'Analyze', "https://psp-analysis-java.herokuapp.com/test/aa/sample/hoge/hoge" %></td>
		<td>
			<%= link_to "Analyze","https://java-psp-analysis.herokuapp.com/mdb/#{f.id}",:method => :post %>
		</td>		
		<td><%#= link_to 'Analyze', mdb_analyze_path(f,format: :json) %></td>
	</tr>
	<br>
<% end %>
<%= form_tag import_mdbs_path, multipart: true do %>
	<%= file_field_tag :file %>
	<%= submit_tag "インポート" %>
<% end %>